### ISSUE TITLE
WSL 下无法使用

### ISSUE THREAD

**Issue by vivian27** [Neur1n/neuims#3]
我的环境是在Win10下WSL1里安装的Ubuntu20.04，neovim通过Plug安装了你的插件且没有修改任何配置。终端我使用的是windows terminal。

操作步骤如下：
打开IMSToggle
微软拼音输入法英文模式输入i
状态栏显示[neuims]Switched to Pinyin
输入内容，仍为英文
按shift切换到中文输入
输入一行中文内容
按esc，状态栏显示[neuims]Switched to English(US)
通过hjkl移动发现仍在中文输入法内

估计是由于插件无法穿透WSL控制windows的IM状态？您这边有测试过或者明确的可用于否的结果么？

**Comment by neur1n** [comment]
我这里测试的结果，应该是插件认为WSL是Linux系统，调用了ibus的命令（默认设置），没有调用Windows的切换输入法命令。

这段时间没空维护这个repo，非常抱歉。

**Comment by vivian27** [comment]
```
function! IMtoEng()
    call system('/mnt/d/bin/win_ims.exe 0x0409')
 endfunction

function! IMtoCN()
     call system('/mnt/d/bin/win_ims.exe 0x0804')
endfunction

autocmd InsertEnter * call IMtoCN()
autocmd InsertLeave * call IMtoEng()
```

我自己参考你的代码，把exe文件抽出来之后解决了，谢谢啦

**Comment by neur1n** [comment]
@vivian27 这给我提供了一个思路，可以让用户自己配置切换命令，倒是一个workaround。
