### ISSUE TITLE
建议：使用微软提供的WM-IME-Control实现中/英切换

### ISSUE THREAD

**Issue by BSDxxxx** [Neur1n/neuims#4]
目前你的插件是在ENG和中文输入法之间切换，如果想在normal模式下输入中文略微麻烦一些，而且还要设置中文输入法的默认语言。

而今天我在[Quicker](https://www.yuque.com/quicker/help/imecontrolj)上发现它可以切换中文输入法的状态，问了作者是用wm-ime-control实现的，希望开发者参考一下。

[xm-ime-control文档](https://docs.microsoft.com/en-us/windows/win32/intl/wm-ime-control)

**Comment by Neur1n** [comment]
谢谢建议

**Comment by roachsinai** [comment]
> 目前你的插件是在ENG和中文输入法之间切换，如果想在normal模式下输入中文略微麻烦一些，而且还要设置中文输入法的默认语言。
> 
> 而今天我在[Quicker](https://www.yuque.com/quicker/help/imecontrolj)上发现它可以切换中文输入法的状态，问了作者是用wm-ime-control实现的，希望开发者参考一下。
> 
> [xm-ime-control文档](https://docs.microsoft.com/en-us/windows/win32/intl/wm-ime-control)

quicker 链接已经失效。

**Comment by BSDxxxx** [comment]
> > 目前你的插件是在ENG和中文输入法之间切换，如果想在normal模式下输入中文略微麻烦一些，而且还要设置中文输入法的默认语言。
> > 而今天我在[Quicker](https://www.yuque.com/quicker/help/imecontrolj)上发现它可以切换中文输入法的状态，问了作者是用wm-ime-control实现的，希望开发者参考一下。
> > [xm-ime-control文档](https://docs.microsoft.com/en-us/windows/win32/intl/wm-ime-control)
> 
> quicker 链接已经失效。

https://getquicker.net/kc/help/doc/imecontrol

**Comment by roachsinai** [comment]
> ​​在最新版的Windows10中，此功能所依赖的Windows接口已经失效。已无法获取和设置输入法状态。

好像是已经失效了。
